version: '2.0'
services:
  ntopng:
    image: edgd1er/ntopng-docker:latest
    build:
      context: .
      dockerfile: Dockerfile.all
      args:
        - aptcacher= #192.168.53.208
        - TZ=Europe/Paris
    restart: always
    environment:
      TZ: "Europe/paris"
      NTOP_UID: 1000
      NTOP_GID: 1000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/ntopng:/var/lib/ntopng
      #- data_ntopng:/var/lib/ntopng
    command: --community -d /var/lib/ntopng -w 0.0.0.0:27833 -r localhost:6379 -Z "/monitor"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: --save 900 1
    volumes:
      - ./data/redis:/data
      #- data_redis:/data/redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge

volumes:
  data_ntopng:
  data_redis: