name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_armhf:
    env:
      DISTRO: armv7hf-debian
      TAG: armhf-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image armhf
        run: docker build -f Dockerfile.armhf --build-arg DISTRO=$DISTRO -t edgd1er/ntop-docker:$TAG .
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/ntop-docker:$TAG

  build_amd64:
    env:
      DISTRO: amd64-ubuntu
      TAG: amd64-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image amd64
        run: docker build -f Dockerfile --build-arg DISTRO=$DISTRO -t edgd1er/ntop-docker:$TAG .
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/ntop-docker:$TAG
